name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please fill out the information below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what went wrong...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. With config '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened? Include error messages if any.
      placeholder: |
        Error: ...
        Traceback: ...
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: frappecli Version
      description: Run `frappecli --version` to get the version
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: Run `python --version`
      placeholder: "Python 3.12.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - macOS
        - Linux
        - Windows
        - Other
    validations:
      required: true

  - type: input
    id: frappe-version
    attributes:
      label: Frappe Version
      description: What version of Frappe are you connecting to?
      placeholder: "v15.0.0"
    validations:
      required: false

  - type: textarea
    id: config
    attributes:
      label: Configuration (Sanitized)
      description: Paste your config.yaml (remove sensitive data!)
      render: yaml
      placeholder: |
        sites:
          mysite:
            url: https://example.com
            # DO NOT include api_key/api_secret
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: Screenshots, logs, etc.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission Checks
      description: Please confirm the following
      options:
        - label: I have searched existing issues to make sure this is not a duplicate
          required: true
        - label: I have removed any sensitive information from my report
          required: true
